"""empty message

Revision ID: 73cd81c73c16
Revises: d4f8162003d5
Create Date: 2018-05-11 19:44:56.643010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cd81c73c16'
down_revision = 'd4f8162003d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jxsources', sa.Column('ext', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jxsources', 'ext')
    # ### end Alembic commands ###
