"""empty message

Revision ID: d4f8162003d5
Revises: 
Create Date: 2018-05-11 18:43:05.319485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f8162003d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('pin', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('isadm', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user'), 'users', ['user'], unique=True)
    op.create_table('zytypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jxsources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zyname', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('uptime', sa.DateTime(), nullable=True),
    sa.Column('countd', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('zytype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zytype_id'], ['zytypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jxsources')
    op.drop_table('zytypes')
    op.drop_index(op.f('ix_users_user'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
